services:
  - type: web
    name: qr-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:10000
